version: "3.7"
services:
  db:
    image: "postgres:11.2"
    container_name: "z_postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    name: z_postgres_data